apiVersion: v1
kind: PersistenVolume 
metadata:
  name: local-pv
  lables: 
    app: local
spec: 
  capacity:
    storage: 1Gi
  accessModes: 
   - ReadWriteOnce
  persistentVolumeReclaimPoliciy: Retain
  storageClassname: local-storage
  hostPath:
  path: /mnt/data
